# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'midisettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        Form.setMinimumSize(QtCore.QSize(500, 400))
        Form.setMaximumSize(QtCore.QSize(500, 400))
        self.midiinputlabel = QtWidgets.QLabel(Form)
        self.midiinputlabel.setGeometry(QtCore.QRect(60, 40, 131, 21))
        self.midiinputlabel.setObjectName("midiinputlabel")
        self.midioutputlabel = QtWidgets.QLabel(Form)
        self.midioutputlabel.setGeometry(QtCore.QRect(60, 130, 131, 21))
        self.midioutputlabel.setObjectName("midioutputlabel")
        self.inputCombo = QtWidgets.QComboBox(Form)
        self.inputCombo.setGeometry(QtCore.QRect(60, 70, 261, 26))
        self.inputCombo.setObjectName("inputCombo")
        self.outputCombo = QtWidgets.QComboBox(Form)
        self.outputCombo.setGeometry(QtCore.QRect(60, 160, 261, 26))
        self.outputCombo.setObjectName("outputCombo")
        self.applyButton = QtWidgets.QPushButton(Form)
        self.applyButton.setGeometry(QtCore.QRect(120, 340, 93, 29))
        self.applyButton.setObjectName("applyButton")
        self.cancelButton = QtWidgets.QPushButton(Form)
        self.cancelButton.setGeometry(QtCore.QRect(290, 340, 93, 29))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.midiinputlabel.setText(_translate("Form", "MIDI Input Device"))
        self.midioutputlabel.setText(_translate("Form", "MIDI Output Device"))
        self.applyButton.setText(_translate("Form", "Apply"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
