# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'midiuser.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 750)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 750))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 750))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.appnamelabel = QtWidgets.QLabel(self.centralwidget)
        self.appnamelabel.setGeometry(QtCore.QRect(490, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.appnamelabel.setFont(font)
        self.appnamelabel.setObjectName("appnamelabel")
        self.serverListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.serverListWidget.setGeometry(QtCore.QRect(210, 220, 681, 241))
        self.serverListWidget.setObjectName("serverListWidget\n"
"")
        self.serverslabel = QtWidgets.QLabel(self.centralwidget)
        self.serverslabel.setGeometry(QtCore.QRect(500, 180, 111, 20))
        self.serverslabel.setObjectName("serverslabel")
        self.usernamelabel = QtWidgets.QLabel(self.centralwidget)
        self.usernamelabel.setGeometry(QtCore.QRect(290, 100, 81, 20))
        self.usernamelabel.setObjectName("usernamelabel")
        self.usernamelineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usernamelineEdit.setGeometry(QtCore.QRect(380, 100, 341, 26))
        self.usernamelineEdit.setObjectName("usernamelineEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(440, 480, 210, 37))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.createRoomButton = QtWidgets.QPushButton(self.layoutWidget)
        self.createRoomButton.setObjectName("createRoomButton")
        self.horizontalLayout.addWidget(self.createRoomButton)
        self.joinRoomButton = QtWidgets.QPushButton(self.layoutWidget)
        self.joinRoomButton.setObjectName("joinRoomButton")
        self.horizontalLayout.addWidget(self.joinRoomButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMIDIsettings = QtWidgets.QAction(MainWindow)
        self.actionMIDIsettings.setObjectName("actionMIDIsettings")
        self.menuSettings.addAction(self.actionMIDIsettings)
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appnamelabel.setText(_translate("MainWindow", "MIDIROOMS"))
        self.serverslabel.setText(_translate("MainWindow", "🌐 Available Rooms"))
        self.usernamelabel.setText(_translate("MainWindow", "Your Name"))
        self.createRoomButton.setText(_translate("MainWindow", "Create Room"))
        self.joinRoomButton.setText(_translate("MainWindow", "Connect"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionMIDIsettings.setText(_translate("MainWindow", "MIDI Settings"))
