# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roomform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_roomwindow(object):
    def setupUi(self, roomwindow):
        roomwindow.setObjectName("roomwindow")
        roomwindow.resize(1100, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(roomwindow.sizePolicy().hasHeightForWidth())
        roomwindow.setSizePolicy(sizePolicy)
        roomwindow.setMinimumSize(QtCore.QSize(1100, 750))
        roomwindow.setMaximumSize(QtCore.QSize(1100, 900))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(roomwindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.muteButton = QtWidgets.QPushButton(roomwindow)
        self.muteButton.setObjectName("muteButton")
        self.horizontalLayout.addWidget(self.muteButton)
        self.routingmanagerButton = QtWidgets.QPushButton(roomwindow)
        self.routingmanagerButton.setObjectName("routingmanagerButton")
        self.horizontalLayout.addWidget(self.routingmanagerButton)
        self.LeaveButton = QtWidgets.QPushButton(roomwindow)
        self.LeaveButton.setObjectName("LeaveButton")
        self.horizontalLayout.addWidget(self.LeaveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(roomwindow)
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 200))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1076, 198))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.uservelocityLayout = QtWidgets.QVBoxLayout()
        self.uservelocityLayout.setObjectName("uservelocityLayout")
        self.verticalLayout_3.addLayout(self.uservelocityLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.loglabel = QtWidgets.QLabel(roomwindow)
        self.loglabel.setObjectName("loglabel")
        self.verticalLayout_2.addWidget(self.loglabel)
        self.logArea = QtWidgets.QTextEdit(roomwindow)
        self.logArea.setObjectName("logArea")
        self.verticalLayout_2.addWidget(self.logArea)
        self.buttonsgroupBox = QtWidgets.QGroupBox(roomwindow)
        self.buttonsgroupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonsgroupBox.setObjectName("buttonsgroupBox")
        self.StopButton = QtWidgets.QPushButton(self.buttonsgroupBox)
        self.StopButton.setGeometry(QtCore.QRect(550, 0, 111, 29))
        self.StopButton.setObjectName("StopButton")
        self.StartButton = QtWidgets.QPushButton(self.buttonsgroupBox)
        self.StartButton.setGeometry(QtCore.QRect(422, 0, 111, 29))
        self.StartButton.setObjectName("StartButton")
        self.verticalLayout_2.addWidget(self.buttonsgroupBox)
        self.PianoWidget = QtWidgets.QWidget(roomwindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PianoWidget.sizePolicy().hasHeightForWidth())
        self.PianoWidget.setSizePolicy(sizePolicy)
        self.PianoWidget.setMinimumSize(QtCore.QSize(1000, 120))
        self.PianoWidget.setObjectName("PianoWidget")
        self.verticalLayout_2.addWidget(self.PianoWidget)

        self.retranslateUi(roomwindow)
        QtCore.QMetaObject.connectSlotsByName(roomwindow)

    def retranslateUi(self, roomwindow):
        _translate = QtCore.QCoreApplication.translate
        roomwindow.setWindowTitle(_translate("roomwindow", "Form"))
        self.muteButton.setText(_translate("roomwindow", "Mute Myself"))
        self.routingmanagerButton.setText(_translate("roomwindow", "Routing Manager"))
        self.LeaveButton.setText(_translate("roomwindow", "Leave Room"))
        self.loglabel.setText(_translate("roomwindow", "MIDI Log"))
        self.buttonsgroupBox.setTitle(_translate("roomwindow", "GroupBox"))
        self.StopButton.setText(_translate("roomwindow", "Stop Recording"))
        self.StartButton.setText(_translate("roomwindow", "Start Recording"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    roomwindow = QtWidgets.QWidget()
    ui = Ui_roomwindow()
    ui.setupUi(roomwindow)
    roomwindow.show()
    sys.exit(app.exec_())
