# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'routingmanager.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_routingDialog(object):
    def setupUi(self, routingDialog):
        routingDialog.setObjectName("routingDialog")
        routingDialog.resize(847, 507)
        routingDialog.setMinimumSize(QtCore.QSize(800, 400))
        self.horizontalLayoutWidget = QtWidgets.QWidget(routingDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(580, 410, 251, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refreshButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.routingTable = QtWidgets.QTableWidget(routingDialog)
        self.routingTable.setGeometry(QtCore.QRect(100, 60, 651, 291))
        self.routingTable.setMinimumSize(QtCore.QSize(200, 0))
        self.routingTable.setColumnCount(4)
        self.routingTable.setObjectName("routingTable")
        self.routingTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.routingTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.routingTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.routingTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.routingTable.setHorizontalHeaderItem(3, item)
        self.routingTable.horizontalHeader().setDefaultSectionSize(215)
        self.routingTable.verticalHeader().setDefaultSectionSize(100)

        self.retranslateUi(routingDialog)
        QtCore.QMetaObject.connectSlotsByName(routingDialog)

    def retranslateUi(self, routingDialog):
        _translate = QtCore.QCoreApplication.translate
        routingDialog.setWindowTitle(_translate("routingDialog", "MIDI Routing Manager"))
        self.refreshButton.setText(_translate("routingDialog", "Refresh"))
        self.cancelButton.setText(_translate("routingDialog", "Cancel"))
        item = self.routingTable.horizontalHeaderItem(0)
        item.setText(_translate("routingDialog", "User"))
        item = self.routingTable.horizontalHeaderItem(1)
        item.setText(_translate("routingDialog", "Stream"))
        item = self.routingTable.horizontalHeaderItem(2)
        item.setText(_translate("routingDialog", "Output"))
        item = self.routingTable.horizontalHeaderItem(3)
        item.setText(_translate("routingDialog", "Channel"))
