# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'username.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(242, 98)
        self.continueButton = QtWidgets.QPushButton(Form)
        self.continueButton.setGeometry(QtCore.QRect(80, 70, 75, 24))
        self.continueButton.setObjectName("continueButton")
        self.usernameLine = QtWidgets.QLineEdit(Form)
        self.usernameLine.setGeometry(QtCore.QRect(60, 30, 116, 22))
        self.usernameLine.setObjectName("usernameLine")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(65, 1, 110, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.continueButton.setText(_translate("Form", "Continue"))
        self.label.setText(_translate("Form", "Enter Your Username"))
