# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'midisettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 600)
        Form.setMinimumSize(QtCore.QSize(900, 600))
        Form.setMaximumSize(QtCore.QSize(900, 600))
        self.midiinputlabel = QtWidgets.QLabel(Form)
        self.midiinputlabel.setGeometry(QtCore.QRect(60, 30, 131, 21))
        self.midiinputlabel.setObjectName("midiinputlabel")
        self.applyButton = QtWidgets.QPushButton(Form)
        self.applyButton.setGeometry(QtCore.QRect(350, 560, 93, 29))
        self.applyButton.setObjectName("applyButton")
        self.cancelButton = QtWidgets.QPushButton(Form)
        self.cancelButton.setGeometry(QtCore.QRect(460, 560, 93, 29))
        self.cancelButton.setObjectName("cancelButton")
        self.inputsList = QtWidgets.QListWidget(Form)
        self.inputsList.setGeometry(QtCore.QRect(50, 60, 801, 481))
        self.inputsList.setAlternatingRowColors(True)
        self.inputsList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.inputsList.setObjectName("inputsList")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.midiinputlabel.setText(_translate("Form", "MIDI Input Device"))
        self.applyButton.setText(_translate("Form", "Apply"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
