# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roomsettings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_roomSettingsWindow(object):
    def setupUi(self, roomSettingsWindow):
        roomSettingsWindow.setObjectName("roomSettingsWindow")
        roomSettingsWindow.resize(697, 471)
        self.centralwidget = QtWidgets.QWidget(roomSettingsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.createRoomButton = QtWidgets.QPushButton(self.centralwidget)
        self.createRoomButton.setObjectName("createRoomButton")
        self.horizontalLayout.addWidget(self.createRoomButton)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        self.maxParticipantsSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.maxParticipantsSpinBox.setMinimum(1)
        self.maxParticipantsSpinBox.setMaximum(12)
        self.maxParticipantsSpinBox.setObjectName("maxParticipantsSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxParticipantsSpinBox)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.recordingCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.recordingCheckBox.setText("")
        self.recordingCheckBox.setObjectName("recordingCheckBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.recordingCheckBox)
        self.roomNameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.roomNameLineEdit.setObjectName("roomNameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.roomNameLineEdit)
        roomSettingsWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(roomSettingsWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 26))
        self.menubar.setObjectName("menubar")
        roomSettingsWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(roomSettingsWindow)
        self.statusbar.setObjectName("statusbar")
        roomSettingsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(roomSettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(roomSettingsWindow)

    def retranslateUi(self, roomSettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        roomSettingsWindow.setWindowTitle(_translate("roomSettingsWindow", "MainWindow"))
        self.label_2.setText(_translate("roomSettingsWindow", "Number Of Participants                                                                        "))
        self.createRoomButton.setText(_translate("roomSettingsWindow", "Create Room"))
        self.cancelButton.setText(_translate("roomSettingsWindow", "Cancel"))
        self.label.setText(_translate("roomSettingsWindow", "Room Name"))
        self.label_3.setText(_translate("roomSettingsWindow", "Enable Recording"))
